version: 2

builds:
  - main: ./cmd/ok2pus
    binary: ok2pus
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: dhrgodms
      name: homebrew-ok2pus
    homepage: "https://github.com/dhrgodms/ok2pus"
    description: "Terminal-based SSH connection manager"
    install: |
      bin.install "ok2pus"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
